spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: 1234


  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

server:
  port: 8081
